operasi penjumlahan

In [1]:
a = [1,2,3]
b = [5,1,2]
c = [0,0,0]

for i in range(len(a)):
    c[i] = a[i]+b[i]
    

In [2]:
c

[6, 3, 5]

In [3]:
import numpy as np
a = [1,2,3,4]
b = [8,9,1,2]
np_a = np.array(a)
np_b = np.array(b)

In [4]:
a + b

[1, 2, 3, 4, 8, 9, 1, 2]

In [5]:
np_a + np_b

array([ 9, 11,  4,  6])

In [6]:
#cek performa
a = [1,2,3,4,5,6,7,8,9,10]
b = [1,1,1,1,1,1,1,1,1,1]

In [8]:
%timeit (a,b)

77.9 ns ± 3.82 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [9]:
a2d = [[1,3],[5,4,5],[7,8]]
a2d = np.array(a2d)
a2d

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_12876\3317907818.py:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a2d = np.array(a2d)


array([list([1, 3]), list([5, 4, 5]), list([7, 8])], dtype=object)

In [10]:
np.ones((5,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [13]:
np.empty(10)

array([nan,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [14]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.arange(1,6,1.5)

array([1. , 2.5, 4. , 5.5])

In [17]:
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [22]:
a = [2,1,3,4,5,6,7,10]
a

[2, 1, 3, 4, 5, 6, 7, 10]

In [26]:
a.reshape([4,2])

AttributeError: 'list' object has no attribute 'reshape'